[jump_hosts]
jump ansible_host=172.25.250.110 ansible_user=cloud-user

[dev1_moodle]
dev1-moodle-1 ansible_host=10.10.1.11 ansible_user=cloud-user
dev1-moodle-2 ansible_host=10.10.1.12 ansible_user=cloud-user

[dev2_moodle]
dev2-moodle-1 ansible_host=10.10.2.11 ansible_user=cloud-user
dev2-moodle-2 ansible_host=10.10.2.12 ansible_user=cloud-user

[moodle:children]
dev1_moodle
dev2_moodle

[moodle:vars]
ansible_ssh_common_args='-o ProxyJump=cloud-user@172.25.250.110'