[jump_hosts]
jump ansible_host=172.25.250.110 ansible_user=cloud-user

[dev1_moodle]
dev1-moodle-1 ansible_host=10.10.1.11 ansible_user=cloud-user developer=dev1 developer_network=10.10.1.0/24
dev1-moodle-2 ansible_host=10.10.1.12 ansible_user=cloud-user developer=dev1 nfs_server_ip=10.10.1.11

[dev2_moodle]
dev2-moodle-1 ansible_host=10.10.2.11 ansible_user=cloud-user developer=dev2 developer_network=10.10.2.0/24
dev2-moodle-2 ansible_host=10.10.2.12 ansible_user=cloud-user developer=dev2 nfs_server_ip=10.10.2.11

[moodle_primary]
dev1-moodle-1
dev2-moodle-1

[moodle_secondary]
dev1-moodle-2
dev2-moodle-2

[moodle:children]
dev1_moodle
dev2_moodle

[moodle:vars]
ansible_ssh_common_args='-o ProxyJump=cloud-user@172.25.250.110'